server:
  port: 8002
spring:
  redis:
    host: 10.112.11.26
    port: 6379
    database: 0
  rabbitmq:
      host: 10.112.11.26
      port: 5672
      username: guest
      password: guest
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${eureka.instance.ip-address}:${server.port}
    #ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://10.112.11.155:9000/eureka/
      #defaultZone: http://10.112.11.155:9000/eureka/,http://10.112.11.186:9000/eureka/,http://10.112.11.14:9000/eureka/,http://10.112.11.108:9000/eureka/,http://10.112.11.164:9000/eureka/
