# server config
server: 
  port: 8002
# spring config
spring: 
  profiles: 
    active: dev
  application: 
    name: micro-smadmin
  boot:
    admin:
      client:
        instance:
          health-url: http://localhost:9003
  mail:
    host: smtp.qq.com
    username: 2272808281@qq.com
    password: kxvobbpdprnceaba
    default-encoding: utf-8
mail:
  fromMail:
    addr: '2272808281@qq.com'
# admin config
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
# pagehelper config
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
# eureka config
eureka: 
  instance:
      #以IP地址注册到服务中心
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      # 服务过期时间eurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍。默认90s
      #lease-expiration-duration-in-seconds: 15
      # 服务刷新时间配置，每隔这个时间会主动心跳一次
      #lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl: 
      defaultZone: http://localhost:9000/eureka/
